services:
  # API Backend (Symfony)
  api:
    build:
      context: ./apps/symfony-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://xandhopp:xandhopp@postgres:5432/xandhopp?serverVersion=15&charset=utf8
      - JWT_PASSPHRASE=xandhopp
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/symfony-api:/app

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=xandhopp
      - POSTGRES_USER=xandhopp
      - POSTGRES_PASSWORD=xandhopp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xandhopp -d xandhopp"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Meilisearch (Search Engine)
  meilisearch:
    image: getmeili/meilisearch:v1.5
    ports:
      - "7700:7700"
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=xandhopp-search-key
    volumes:
      - meilisearch_data:/meili_data

  # Redis (Cache & Sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # MinIO (S3-compatible storage)
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=xandhopp
      - MINIO_ROOT_PASSWORD=xandhopp123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  meilisearch_data:
  redis_data:
  minio_data:
