"""
Länderdaten für XNTOP Importer
Alle Länder der Welt nach Kontinenten (Africa, Americas, Asia, Europe, Oceania)
"""

COUNTRIES_BY_CONTINENT = {
    "Africa": [
        {"name": "Algeria", "iso": "DZA", "wikipedia_slug": "Algeria"},
        {"name": "Angola", "iso": "AGO", "wikipedia_slug": "Angola"},
        {"name": "Benin", "iso": "BEN", "wikipedia_slug": "Benin"},
        {"name": "Botswana", "iso": "BWA", "wikipedia_slug": "Botswana"},
        {"name": "Burkina Faso", "iso": "BFA", "wikipedia_slug": "Burkina_Faso"},
        {"name": "Burundi", "iso": "BDI", "wikipedia_slug": "Burundi"},
        {"name": "Cameroon", "iso": "CMR", "wikipedia_slug": "Cameroon"},
        {"name": "Cape Verde", "iso": "CPV", "wikipedia_slug": "Cape_Verde"},
        {"name": "Central African Republic", "iso": "CAF", "wikipedia_slug": "Central_African_Republic"},
        {"name": "Chad", "iso": "TCD", "wikipedia_slug": "Chad"},
        {"name": "Comoros", "iso": "COM", "wikipedia_slug": "Comoros"},
        {"name": "Democratic Republic of the Congo", "iso": "COD", "wikipedia_slug": "Democratic_Republic_of_the_Congo"},
        {"name": "Republic of the Congo", "iso": "COG", "wikipedia_slug": "Republic_of_the_Congo"},
        {"name": "Djibouti", "iso": "DJI", "wikipedia_slug": "Djibouti"},
        {"name": "Egypt", "iso": "EGY", "wikipedia_slug": "Egypt"},
        {"name": "Equatorial Guinea", "iso": "GNQ", "wikipedia_slug": "Equatorial_Guinea"},
        {"name": "Eritrea", "iso": "ERI", "wikipedia_slug": "Eritrea"},
        {"name": "Eswatini", "iso": "SWZ", "wikipedia_slug": "Eswatini"},
        {"name": "Ethiopia", "iso": "ETH", "wikipedia_slug": "Ethiopia"},
        {"name": "Gabon", "iso": "GAB", "wikipedia_slug": "Gabon"},
        {"name": "Gambia", "iso": "GMB", "wikipedia_slug": "Gambia"},
        {"name": "Ghana", "iso": "GHA", "wikipedia_slug": "Ghana"},
        {"name": "Guinea", "iso": "GIN", "wikipedia_slug": "Guinea"},
        {"name": "Guinea-Bissau", "iso": "GNB", "wikipedia_slug": "Guinea-Bissau"},
        {"name": "Ivory Coast", "iso": "CIV", "wikipedia_slug": "Ivory_Coast"},
        {"name": "Kenya", "iso": "KEN", "wikipedia_slug": "Kenya"},
        {"name": "Lesotho", "iso": "LSO", "wikipedia_slug": "Lesotho"},
        {"name": "Liberia", "iso": "LBR", "wikipedia_slug": "Liberia"},
        {"name": "Libya", "iso": "LBY", "wikipedia_slug": "Libya"},
        {"name": "Madagascar", "iso": "MDG", "wikipedia_slug": "Madagascar"},
        {"name": "Malawi", "iso": "MWI", "wikipedia_slug": "Malawi"},
        {"name": "Mali", "iso": "MLI", "wikipedia_slug": "Mali"},
        {"name": "Mauritania", "iso": "MRT", "wikipedia_slug": "Mauritania"},
        {"name": "Mauritius", "iso": "MUS", "wikipedia_slug": "Mauritius"},
        {"name": "Morocco", "iso": "MAR", "wikipedia_slug": "Morocco"},
        {"name": "Mozambique", "iso": "MOZ", "wikipedia_slug": "Mozambique"},
        {"name": "Namibia", "iso": "NAM", "wikipedia_slug": "Namibia"},
        {"name": "Niger", "iso": "NER", "wikipedia_slug": "Niger"},
        {"name": "Nigeria", "iso": "NGA", "wikipedia_slug": "Nigeria"},
        {"name": "Rwanda", "iso": "RWA", "wikipedia_slug": "Rwanda"},
        {"name": "São Tomé and Príncipe", "iso": "STP", "wikipedia_slug": "São_Tomé_and_Príncipe"},
        {"name": "Senegal", "iso": "SEN", "wikipedia_slug": "Senegal"},
        {"name": "Seychelles", "iso": "SYC", "wikipedia_slug": "Seychelles"},
        {"name": "Sierra Leone", "iso": "SLE", "wikipedia_slug": "Sierra_Leone"},
        {"name": "Somalia", "iso": "SOM", "wikipedia_slug": "Somalia"},
        {"name": "South Africa", "iso": "ZAF", "wikipedia_slug": "South_Africa"},
        {"name": "South Sudan", "iso": "SSD", "wikipedia_slug": "South_Sudan"},
        {"name": "Sudan", "iso": "SDN", "wikipedia_slug": "Sudan"},
        {"name": "Tanzania", "iso": "TZA", "wikipedia_slug": "Tanzania"},
        {"name": "Togo", "iso": "TGO", "wikipedia_slug": "Togo"},
        {"name": "Tunisia", "iso": "TUN", "wikipedia_slug": "Tunisia"},
        {"name": "Uganda", "iso": "UGA", "wikipedia_slug": "Uganda"},
        {"name": "Zambia", "iso": "ZMB", "wikipedia_slug": "Zambia"},
        {"name": "Zimbabwe", "iso": "ZWE", "wikipedia_slug": "Zimbabwe"},
    ],
    
    "Americas": [
        {"name": "Antigua and Barbuda", "iso": "ATG", "wikipedia_slug": "Antigua_and_Barbuda"},
        {"name": "Argentina", "iso": "ARG", "wikipedia_slug": "Argentina"},
        {"name": "Bahamas", "iso": "BHS", "wikipedia_slug": "Bahamas"},
        {"name": "Barbados", "iso": "BRB", "wikipedia_slug": "Barbados"},
        {"name": "Belize", "iso": "BLZ", "wikipedia_slug": "Belize"},
        {"name": "Bolivia", "iso": "BOL", "wikipedia_slug": "Bolivia"},
        {"name": "Brazil", "iso": "BRA", "wikipedia_slug": "Brazil"},
        {"name": "Canada", "iso": "CAN", "wikipedia_slug": "Canada"},
        {"name": "Chile", "iso": "CHL", "wikipedia_slug": "Chile"},
        {"name": "Colombia", "iso": "COL", "wikipedia_slug": "Colombia"},
        {"name": "Costa Rica", "iso": "CRI", "wikipedia_slug": "Costa_Rica"},
        {"name": "Cuba", "iso": "CUB", "wikipedia_slug": "Cuba"},
        {"name": "Dominica", "iso": "DMA", "wikipedia_slug": "Dominica"},
        {"name": "Dominican Republic", "iso": "DOM", "wikipedia_slug": "Dominican_Republic"},
        {"name": "Ecuador", "iso": "ECU", "wikipedia_slug": "Ecuador"},
        {"name": "El Salvador", "iso": "SLV", "wikipedia_slug": "El_Salvador"},
        {"name": "Grenada", "iso": "GRD", "wikipedia_slug": "Grenada"},
        {"name": "Guatemala", "iso": "GTM", "wikipedia_slug": "Guatemala"},
        {"name": "Guyana", "iso": "GUY", "wikipedia_slug": "Guyana"},
        {"name": "Haiti", "iso": "HTI", "wikipedia_slug": "Haiti"},
        {"name": "Honduras", "iso": "HND", "wikipedia_slug": "Honduras"},
        {"name": "Jamaica", "iso": "JAM", "wikipedia_slug": "Jamaica"},
        {"name": "Mexico", "iso": "MEX", "wikipedia_slug": "Mexico"},
        {"name": "Nicaragua", "iso": "NIC", "wikipedia_slug": "Nicaragua"},
        {"name": "Panama", "iso": "PAN", "wikipedia_slug": "Panama"},
        {"name": "Paraguay", "iso": "PRY", "wikipedia_slug": "Paraguay"},
        {"name": "Peru", "iso": "PER", "wikipedia_slug": "Peru"},
        {"name": "Saint Kitts and Nevis", "iso": "KNA", "wikipedia_slug": "Saint_Kitts_and_Nevis"},
        {"name": "Saint Lucia", "iso": "LCA", "wikipedia_slug": "Saint_Lucia"},
        {"name": "Saint Vincent and the Grenadines", "iso": "VCT", "wikipedia_slug": "Saint_Vincent_and_the_Grenadines"},
        {"name": "Suriname", "iso": "SUR", "wikipedia_slug": "Suriname"},
        {"name": "Trinidad and Tobago", "iso": "TTO", "wikipedia_slug": "Trinidad_and_Tobago"},
        {"name": "United States", "iso": "USA", "wikipedia_slug": "United_States"},
        {"name": "Uruguay", "iso": "URY", "wikipedia_slug": "Uruguay"},
        {"name": "Venezuela", "iso": "VEN", "wikipedia_slug": "Venezuela"},
    ],
    
    "Asia": [
        {"name": "Afghanistan", "iso": "AFG", "wikipedia_slug": "Afghanistan"},
        {"name": "Armenia", "iso": "ARM", "wikipedia_slug": "Armenia"},
        {"name": "Azerbaijan", "iso": "AZE", "wikipedia_slug": "Azerbaijan"},
        {"name": "Bahrain", "iso": "BHR", "wikipedia_slug": "Bahrain"},
        {"name": "Bangladesh", "iso": "BGD", "wikipedia_slug": "Bangladesh"},
        {"name": "Bhutan", "iso": "BTN", "wikipedia_slug": "Bhutan"},
        {"name": "Brunei", "iso": "BRN", "wikipedia_slug": "Brunei"},
        {"name": "Cambodia", "iso": "KHM", "wikipedia_slug": "Cambodia"},
        {"name": "China", "iso": "CHN", "wikipedia_slug": "China"},
        {"name": "Cyprus", "iso": "CYP", "wikipedia_slug": "Cyprus"},
        {"name": "East Timor", "iso": "TLS", "wikipedia_slug": "East_Timor"},
        {"name": "Georgia", "iso": "GEO", "wikipedia_slug": "Georgia_(country)"},
        {"name": "India", "iso": "IND", "wikipedia_slug": "India"},
        {"name": "Indonesia", "iso": "IDN", "wikipedia_slug": "Indonesia"},
        {"name": "Iran", "iso": "IRN", "wikipedia_slug": "Iran"},
        {"name": "Iraq", "iso": "IRQ", "wikipedia_slug": "Iraq"},
        {"name": "Israel", "iso": "ISR", "wikipedia_slug": "Israel"},
        {"name": "Japan", "iso": "JPN", "wikipedia_slug": "Japan"},
        {"name": "Jordan", "iso": "JOR", "wikipedia_slug": "Jordan"},
        {"name": "Kazakhstan", "iso": "KAZ", "wikipedia_slug": "Kazakhstan"},
        {"name": "Kuwait", "iso": "KWT", "wikipedia_slug": "Kuwait"},
        {"name": "Kyrgyzstan", "iso": "KGZ", "wikipedia_slug": "Kyrgyzstan"},
        {"name": "Laos", "iso": "LAO", "wikipedia_slug": "Laos"},
        {"name": "Lebanon", "iso": "LBN", "wikipedia_slug": "Lebanon"},
        {"name": "Malaysia", "iso": "MYS", "wikipedia_slug": "Malaysia"},
        {"name": "Maldives", "iso": "MDV", "wikipedia_slug": "Maldives"},
        {"name": "Mongolia", "iso": "MNG", "wikipedia_slug": "Mongolia"},
        {"name": "Myanmar", "iso": "MMR", "wikipedia_slug": "Myanmar"},
        {"name": "Nepal", "iso": "NPL", "wikipedia_slug": "Nepal"},
        {"name": "North Korea", "iso": "PRK", "wikipedia_slug": "North_Korea"},
        {"name": "Oman", "iso": "OMN", "wikipedia_slug": "Oman"},
        {"name": "Pakistan", "iso": "PAK", "wikipedia_slug": "Pakistan"},
        {"name": "Palestine", "iso": "PSE", "wikipedia_slug": "State_of_Palestine"},
        {"name": "Philippines", "iso": "PHL", "wikipedia_slug": "Philippines"},
        {"name": "Qatar", "iso": "QAT", "wikipedia_slug": "Qatar"},
        {"name": "Saudi Arabia", "iso": "SAU", "wikipedia_slug": "Saudi_Arabia"},
        {"name": "Singapore", "iso": "SGP", "wikipedia_slug": "Singapore"},
        {"name": "South Korea", "iso": "KOR", "wikipedia_slug": "South_Korea"},
        {"name": "Sri Lanka", "iso": "LKA", "wikipedia_slug": "Sri_Lanka"},
        {"name": "Syria", "iso": "SYR", "wikipedia_slug": "Syria"},
        {"name": "Taiwan", "iso": "TWN", "wikipedia_slug": "Taiwan"},
        {"name": "Tajikistan", "iso": "TJK", "wikipedia_slug": "Tajikistan"},
        {"name": "Thailand", "iso": "THA", "wikipedia_slug": "Thailand"},
        {"name": "Turkey", "iso": "TUR", "wikipedia_slug": "Turkey"},
        {"name": "Turkmenistan", "iso": "TKM", "wikipedia_slug": "Turkmenistan"},
        {"name": "United Arab Emirates", "iso": "ARE", "wikipedia_slug": "United_Arab_Emirates"},
        {"name": "Uzbekistan", "iso": "UZB", "wikipedia_slug": "Uzbekistan"},
        {"name": "Vietnam", "iso": "VNM", "wikipedia_slug": "Vietnam"},
        {"name": "Yemen", "iso": "YEM", "wikipedia_slug": "Yemen"},
    ],
    
    "Europe": [
        {"name": "Albania", "iso": "ALB", "wikipedia_slug": "Albania"},
        {"name": "Andorra", "iso": "AND", "wikipedia_slug": "Andorra"},
        {"name": "Austria", "iso": "AUT", "wikipedia_slug": "Austria"},
        {"name": "Belarus", "iso": "BLR", "wikipedia_slug": "Belarus"},
        {"name": "Belgium", "iso": "BEL", "wikipedia_slug": "Belgium"},
        {"name": "Bosnia and Herzegovina", "iso": "BIH", "wikipedia_slug": "Bosnia_and_Herzegovina"},
        {"name": "Bulgaria", "iso": "BGR", "wikipedia_slug": "Bulgaria"},
        {"name": "Croatia", "iso": "HRV", "wikipedia_slug": "Croatia"},
        {"name": "Czech Republic", "iso": "CZE", "wikipedia_slug": "Czech_Republic"},
        {"name": "Denmark", "iso": "DNK", "wikipedia_slug": "Denmark"},
        {"name": "Estonia", "iso": "EST", "wikipedia_slug": "Estonia"},
        {"name": "Finland", "iso": "FIN", "wikipedia_slug": "Finland"},
        {"name": "France", "iso": "FRA", "wikipedia_slug": "France"},
        {"name": "Germany", "iso": "DEU", "wikipedia_slug": "Germany"},
        {"name": "Greece", "iso": "GRC", "wikipedia_slug": "Greece"},
        {"name": "Hungary", "iso": "HUN", "wikipedia_slug": "Hungary"},
        {"name": "Iceland", "iso": "ISL", "wikipedia_slug": "Iceland"},
        {"name": "Ireland", "iso": "IRL", "wikipedia_slug": "Ireland"},
        {"name": "Italy", "iso": "ITA", "wikipedia_slug": "Italy"},
        {"name": "Kosovo", "iso": "XKX", "wikipedia_slug": "Kosovo"},
        {"name": "Latvia", "iso": "LVA", "wikipedia_slug": "Latvia"},
        {"name": "Liechtenstein", "iso": "LIE", "wikipedia_slug": "Liechtenstein"},
        {"name": "Lithuania", "iso": "LTU", "wikipedia_slug": "Lithuania"},
        {"name": "Luxembourg", "iso": "LUX", "wikipedia_slug": "Luxembourg"},
        {"name": "Malta", "iso": "MLT", "wikipedia_slug": "Malta"},
        {"name": "Moldova", "iso": "MDA", "wikipedia_slug": "Moldova"},
        {"name": "Monaco", "iso": "MCO", "wikipedia_slug": "Monaco"},
        {"name": "Montenegro", "iso": "MNE", "wikipedia_slug": "Montenegro"},
        {"name": "Netherlands", "iso": "NLD", "wikipedia_slug": "Netherlands"},
        {"name": "North Macedonia", "iso": "MKD", "wikipedia_slug": "North_Macedonia"},
        {"name": "Norway", "iso": "NOR", "wikipedia_slug": "Norway"},
        {"name": "Poland", "iso": "POL", "wikipedia_slug": "Poland"},
        {"name": "Portugal", "iso": "PRT", "wikipedia_slug": "Portugal"},
        {"name": "Romania", "iso": "ROU", "wikipedia_slug": "Romania"},
        {"name": "Russia", "iso": "RUS", "wikipedia_slug": "Russia"},
        {"name": "San Marino", "iso": "SMR", "wikipedia_slug": "San_Marino"},
        {"name": "Serbia", "iso": "SRB", "wikipedia_slug": "Serbia"},
        {"name": "Slovakia", "iso": "SVK", "wikipedia_slug": "Slovakia"},
        {"name": "Slovenia", "iso": "SVN", "wikipedia_slug": "Slovenia"},
        {"name": "Spain", "iso": "ESP", "wikipedia_slug": "Spain"},
        {"name": "Sweden", "iso": "SWE", "wikipedia_slug": "Sweden"},
        {"name": "Switzerland", "iso": "CHE", "wikipedia_slug": "Switzerland"},
        {"name": "Ukraine", "iso": "UKR", "wikipedia_slug": "Ukraine"},
        {"name": "United Kingdom", "iso": "GBR", "wikipedia_slug": "United_Kingdom"},
        {"name": "Vatican City", "iso": "VAT", "wikipedia_slug": "Vatican_City"},
    ],
    
    "Oceania": [
        {"name": "Australia", "iso": "AUS", "wikipedia_slug": "Australia"},
        {"name": "Fiji", "iso": "FJI", "wikipedia_slug": "Fiji"},
        {"name": "Kiribati", "iso": "KIR", "wikipedia_slug": "Kiribati"},
        {"name": "Marshall Islands", "iso": "MHL", "wikipedia_slug": "Marshall_Islands"},
        {"name": "Micronesia", "iso": "FSM", "wikipedia_slug": "Micronesia"},
        {"name": "Nauru", "iso": "NRU", "wikipedia_slug": "Nauru"},
        {"name": "New Zealand", "iso": "NZL", "wikipedia_slug": "New_Zealand"},
        {"name": "Palau", "iso": "PLW", "wikipedia_slug": "Palau"},
        {"name": "Papua New Guinea", "iso": "PNG", "wikipedia_slug": "Papua_New_Guinea"},
        {"name": "Samoa", "iso": "WSM", "wikipedia_slug": "Samoa"},
        {"name": "Solomon Islands", "iso": "SLB", "wikipedia_slug": "Solomon_Islands"},
        {"name": "Tonga", "iso": "TON", "wikipedia_slug": "Tonga"},
        {"name": "Tuvalu", "iso": "TUV", "wikipedia_slug": "Tuvalu"},
        {"name": "Vanuatu", "iso": "VUT", "wikipedia_slug": "Vanuatu"},
        # Territories and Dependencies
        {"name": "American Samoa", "iso": "ASM", "wikipedia_slug": "American_Samoa"},
        {"name": "Cook Islands", "iso": "COK", "wikipedia_slug": "Cook_Islands"},
        {"name": "French Polynesia", "iso": "PYF", "wikipedia_slug": "French_Polynesia"},
        {"name": "Guam", "iso": "GUM", "wikipedia_slug": "Guam"},
        {"name": "New Caledonia", "iso": "NCL", "wikipedia_slug": "New_Caledonia"},
        {"name": "Niue", "iso": "NIU", "wikipedia_slug": "Niue"},
        {"name": "Norfolk Island", "iso": "NFK", "wikipedia_slug": "Norfolk_Island"},
        {"name": "Northern Mariana Islands", "iso": "MNP", "wikipedia_slug": "Northern_Mariana_Islands"},
        {"name": "Pitcairn Islands", "iso": "PCN", "wikipedia_slug": "Pitcairn_Islands"},
        {"name": "Tokelau", "iso": "TKL", "wikipedia_slug": "Tokelau"},
        {"name": "Wallis and Futuna", "iso": "WLF", "wikipedia_slug": "Wallis_and_Futuna"},
    ]
}

# Unterstützte Sprachen
SUPPORTED_LANGUAGES = {
    "en": "English",
    "de": "Deutsch", 
    "es": "Español",
    "zh": "中文",
    "hi": "हिन्दी"
}

# Wikipedia-Sprachcodes
WIKIPEDIA_LANGUAGE_CODES = {
    "en": "en",
    "de": "de", 
    "es": "es",
    "zh": "zh",
    "hi": "hi"
}
