// This file will be auto-generated by openapi-typescript
// Run: pnpm --filter @xandhopp/shared run generate:openapi

export interface paths {
  "/api/auth/register": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            email: string;
            password: string;
            firstName: string;
            lastName: string;
          };
        };
      };
      responses: {
        201: {
          content: {
            "application/json": {
              message: string;
              user: {
                id: string;
                email: string;
                firstName: string;
                lastName: string;
                emailVerified: boolean;
              };
            };
          };
        };
        400: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/auth/login": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            email: string;
            password: string;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              token: string;
              user: {
                id: string;
                email: string;
                firstName: string;
                lastName: string;
                emailVerified: boolean;
              };
            };
          };
        };
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/auth/profile": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              id: string;
              email: string;
              firstName: string;
              lastName: string;
              emailVerified: boolean;
            };
          };
        };
      };
    };
    put: {
      requestBody: {
        content: {
          "application/json": {
            firstName?: string;
            lastName?: string;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              message: string;
              user: {
                id: string;
                email: string;
                firstName: string;
                lastName: string;
                emailVerified: boolean;
              };
            };
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    User: {
      id: string;
      email: string;
      firstName: string;
      lastName: string;
      emailVerified: boolean;
    };
    AuthResponse: {
      token: string;
      user: components["schemas"]["User"];
    };
    ErrorResponse: {
      error: string;
    };
  };
}

export interface operations {}
