// This file will be auto-generated by openapi-typescript
// Run: pnpm --filter @portalis/shared run generate:openapi

export interface paths {}
export interface components {}
export interface operations {}
