nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^https?://(localhost|xandhopp\.local|admin\.xandhopp\.local|api\.xandhopp\.local)(:[0-9]+)?$']
        allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        expose_headers: ['Link']
        max_age: 3600
        hosts: []
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['^https?://(localhost|xandhopp\.local|admin\.xandhopp\.local|api\.xandhopp\.local)(:[0-9]+)?$']
            allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
